// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABeHSxDQZ_IlMlx5gQwiV7ZbN8xUaTTdw',
    appId: '1:606399098877:web:300eee5dabf75c0697b394',
    messagingSenderId: '606399098877',
    projectId: 'capstone-7accc',
    authDomain: 'capstone-7accc.firebaseapp.com',
    storageBucket: 'capstone-7accc.appspot.com',
    databaseURL: 'https://capstone-7accc-default-rtdb.firebaseio.com',
    measurementId: 'G-E1G2B9JZYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADcOR7LDyLqIhMrMCMiCSJKqimTcbiKgM',
    appId: '1:606399098877:android:e9b6d7df3af67cb597b394',
    messagingSenderId: '606399098877',
    projectId: 'capstone-7accc',
    storageBucket: 'capstone-7accc.appspot.com',
    databaseURL: 'https://capstone-7accc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3WksgkvXs9kuZGa1gyDk206lMYIzw3V8',
    appId: '1:606399098877:ios:f5d9cb955e739e6f97b394',
    messagingSenderId: '606399098877',
    projectId: 'capstone-7accc',
    storageBucket: 'capstone-7accc.appspot.com',
    iosBundleId: 'com.example.stealthwearapp',
    databaseURL: 'https://capstone-7accc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3WksgkvXs9kuZGa1gyDk206lMYIzw3V8',
    appId: '1:606399098877:ios:f5d9cb955e739e6f97b394',
    messagingSenderId: '606399098877',
    projectId: 'capstone-7accc',
    storageBucket: 'capstone-7accc.appspot.com',
    iosBundleId: 'com.example.stealthwearapp',
    databaseURL: 'https://capstone-7accc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABeHSxDQZ_IlMlx5gQwiV7ZbN8xUaTTdw',
    appId: '1:606399098877:web:9dddd007c29c230797b394',
    messagingSenderId: '606399098877',
    projectId: 'capstone-7accc',
    authDomain: 'capstone-7accc.firebaseapp.com',
    storageBucket: 'capstone-7accc.appspot.com',
    databaseURL: 'https://capstone-7accc-default-rtdb.firebaseio.com',
    measurementId: 'G-6H0Z8X3Q63',
  );
}
